services:
  postgres:
    image: postgres:15-alpine
    container_name: buildmaster-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: buildmaster_db
      POSTGRES_USER: mrlii
      POSTGRES_PASSWORD: buildmaster@v1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - buildmaster-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mrlii -d buildmaster_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongodb:
    image: mongo:7.0
    container_name: buildmaster-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: buildmaster_audit
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - buildmaster-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5

  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: buildmaster-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - buildmaster-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:9.0.0
    container_name: buildmaster-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - buildmaster-network
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus


volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  grafana_data:
    driver: local

networks:
  buildmaster-network:
    driver: bridge