global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'springboot-app'
    static_configs:
      - targets: ['springboot-app:8080']
    metrics_path: '/actuator/prometheus'